# Generated by Django 3.1.6 on 2021-10-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysimpleblog', '0003_auto_20211006_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
