# Generated by Django 3.1.6 on 2021-10-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysimpleblog', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
