# Generated by Django 3.1.6 on 2021-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysimpleblog', '0009_auto_20211012_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='Click Link Above to read Blog post', max_length=255),
        ),
    ]
